version: "3.8"

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ebdb
      MB_DB_PORT: 5432
      MB_DB_USER: webpack
      MB_DB_PASS: 4sv.F4Njc=YKSSJ
      MB_DB_HOST: metabase-docker.cohszsjzeadj.us-east-1.rds.amazonaws.com
    expose:
      - "3000"
    networks:
      - metabase-net
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro  # ✅ Corrección clave
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - metabase
    networks:
      - metabase-net
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: ""
    command: > 
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot 
      --email dbytesrl@gmail.com --agree-tos --no-eff-email 
      -d metabase.webpack.com.ar"

networks:
  metabase-net:
    driver: bridge
